

export default [
        {
        label:'账号管理',
        to:'',
        children:[
                        {
                label:'管理员账号管理',
                to:'/admin/admins',
            },
                        {
                label:'管理员账号添加',
                to:'/admin/adminsadd',
            },
                        {
                label:'注册用户管理',
                to:'/admin/yonghu',
            },
                        {
                label:'添加新用户',
                to:'/admin/yonghuadd',
            },
                        {
                label:'密码修改',
                to:'/admin/mod',
            },
                    ]
    },
        {
        label:'地区管理',
        to:'',
        children:[
                        {
                label:'地区添加',
                to:'/admin/diquadd',
            },
                        {
                label:'地区查询',
                to:'/admin/diqu',
            },
                    ]
    },
        {
        label:'景点信息管理',
        to:'',
        children:[
                        {
                label:'景点信息添加',
                to:'/admin/jingdianxinxiadd',
            },
                        {
                label:'景点信息查询',
                to:'/admin/jingdianxinxi',
            },
                    ]
    },
        {
        label:'地方饭店管理',
        to:'',
        children:[
                        {
                label:'饭店分类添加',
                to:'/admin/fandianfenleiadd',
            },
                        {
                label:'饭店分类查询',
                to:'/admin/fandianfenlei',
            },
                        {
                label:'地方饭店添加',
                to:'/admin/difangfandianadd',
            },
                        {
                label:'地方饭店查询',
                to:'/admin/difangfandian',
            },
                    ]
    },
        {
        label:'告示管理',
        to:'',
        children:[
                        {
                label:'分类添加',
                to:'/admin/xinwenfenleiadd',
            },
                        {
                label:'分类查询',
                to:'/admin/xinwenfenlei',
            },
                        {
                label:'告示添加',
                to:'/admin/xinwenxinxiadd',
            },
                        {
                label:'告示查询',
                to:'/admin/xinwenxinxi',
            },
                    ]
    },


    {
        label:'档案管理',
        to:'',
        children:[
            {
                label:'档案添加',
                to:'/admin/danganadd',
            },
            {
                label:'档案查询',
                to:'/admin/dangan',
            },
        ]
    },



        {
        label:'系统管理',
        to:'',
        children:[
                        {
                label:'轮播图添加',
                to:'/admin/lunbotuadd',
            },
                        {
                label:'轮播图查询',
                to:'/admin/lunbotu',
            },
                        {
                label:'投诉管理',
                to:'/admin/liuyanban',
            },
                    ]
    },
    ]
